name: PR TEST SIMPLE VERSION (NPU)

on:
  push:
    branches: [ "main" ]
    paths:
      - "python/**"
      - "scripts/**"
      - "test/**"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "python/**"
      - "scripts/**"
      - "test/**"
      - ".github/workflows/**"
jobs:
  unit-test-basic:
    runs-on: NpuTestRunner0

    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1.alpha003-910b-ubuntu22.04-py3.11
      options: |
              --device=/dev/davinci0:/dev/davinci0 --device=/dev/davinci2:/dev/davinci2 --device=/dev/davinci3:/dev/davinci3  --device=/dev/davinci4:/dev/davinci4 --device=/dev/davinci5:/dev/davinci5 --device=/dev/davinci6:/dev/davinci6 --device=/dev/davinci7:/dev/davinci7 --device=/dev/davinci_manager --device=/dev/devmm_svm --device=/dev/hisi_hdc -v /usr/local/Ascend/driver/:/usr/local/Ascend/driver -v /etc/ascend_install.info:/etc/ascend_install.info -v /data/models/:/data/models/ -v /etc/hccn.conf:/etc/hccn.conf -v /usr/local/sbin/npu-smi:/usr/local/sbin/npu-smi -v/home/l00623338/pkg:/home/l00623338/pkg

    steps:
      - name: dns avoid
        run: |
          cp /etc/hosts ./
          sed -i '$a 140.82.114.26                 alive.github.com' ./hosts
          sed -i '$a 20.205.243.168                api.github.com' ./hosts
          sed -i '$a 140.82.112.22                 api.individual.githubcopilot.com' ./hosts
          sed -i '$a 185.199.110.133               avatars.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               avatars0.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               avatars1.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               avatars2.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               avatars3.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               avatars4.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               avatars5.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               camo.githubusercontent.com' ./hosts
          sed -i '$a 140.82.112.21                 central.github.com' ./hosts
          sed -i '$a 185.199.110.133               cloud.githubusercontent.com' ./hosts
          sed -i '$a 20.205.243.165                codeload.github.com' ./hosts
          sed -i '$a 140.82.112.21                 collector.github.com' ./hosts
          sed -i '$a 185.199.110.133               desktop.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               favicons.githubusercontent.com' ./hosts
          sed -i '$a 20.205.243.166                gist.github.com' ./hosts
          sed -i '$a 3.5.2.50                      github-cloud.s3.amazonaws.com' ./hosts
          sed -i '$a 16.15.177.48                  github-com.s3.amazonaws.com' ./hosts
          sed -i '$a 3.5.27.214                    github-production-release-asset-2e65be.s3.amazonaws.com' ./hosts
          sed -i '$a 16.15.176.243                 github-production-repository-file-5c1aeb.s3.amazonaws.com' ./hosts
          sed -i '$a 52.217.74.28                  github-production-user-asset-6210df.s3.amazonaws.com' ./hosts
          sed -i '$a 192.0.66.2                    github.blog' ./hosts
          sed -i '$a 140.82.112.3                  github.com' ./hosts
          sed -i '$a 140.82.114.17                 github.community' ./hosts
          sed -i '$a 185.199.111.154               github.githubassets.com' ./hosts
          sed -i '$a 151.101.193.194               github.global.ssl.fastly.net' ./hosts
          sed -i '$a 185.199.111.153               github.io' ./hosts
          sed -i '$a 185.199.110.133               github.map.fastly.net' ./hosts
          sed -i '$a 185.199.111.153               githubstatus.com' ./hosts
          sed -i '$a 140.82.114.25                 live.github.com' ./hosts
          sed -i '$a 185.199.110.133               media.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               objects.githubusercontent.com' ./hosts
          sed -i '$a 13.107.42.16                  pipelines.actions.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               raw.githubusercontent.com' ./hosts
          sed -i '$a 185.199.110.133               user-images.githubusercontent.com' ./hosts
          sed -i '$a 13.107.246.73                 vscode.dev  # Timeout' ./hosts
          sed -i '$a 140.82.114.22                 education.github.com' ./hosts
          sed -i '$a 185.199.110.133               private-user-images.githubusercontent.com' ./hosts
          sed -i '$a 54.87.120.168                 hub.docker.com' ./hosts
          cp ./hosts /etc/hosts
          cat /etc/hosts
          echo "Git clone successfully"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          bash scripts/npu_ci_install_dependency.sh
          echo "npu_ci_install_dependency installed successfully"
          bash /home/l00623338/pkg/Ascend-cann-toolkit_9.2.RC1*.run --install
          bash /home/l00623338/pkg/Ascend-cann-kernels-*.run --install
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          echo "pkg installed successfully"
      - name: Run test
        run: |
          echo "All jobs completed successfully"
  finish:
    if: always()
    needs: [ unit-test-basic ]
    runs-on: NpuTestRunner0
    steps:
      - name: Check all dependent job statuses
        run: |
          echo "All jobs completed successfully"
          exit 0
